services:
  - type: web
    name: hrms-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hrms.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hrms.settings
      - key: PYTHON_VERSION
        value: 3.11
